---
title: "Performance"
---

This article documents the performance of the `gtfsrealtime` package, using one day of bus position data (~2.8 million observations) in New York City. To provide a baseline, it also reads the same data with `RProtoBuf`, the only other actively-maintained R package we are aware of that can read GTFS-realtime.




``` r
library(gtfsrealtime)
library(RProtoBuf)
```

## Getting data

First, we download the data, as it is too large to ship with the package.


``` r
suppressMessages({
  if (!file.exists("nyc-bus-demo.zip")) {
    download.file(
      "https://files.indicatrix.org/gtfsrealtime-r/nyc-bus-demo.zip",
      "nyc-bus-demo.zip"
    )
  }
})
```

## Reading with `gtfsrealtime`

`gtfsrealtime` can read directly from the ZIP archive. We use `as_sf` here, since that is used in the paper, but when we go head to head with RProtoBuf below we don't to make a fair comparison.


``` r
system.time({data_gtfsrealtime = read_gtfsrt_positions("nyc-bus-demo.zip", "America/New_York", as_sf=T)})
#>    user  system elapsed 
#>  11.474   3.604  17.796
```

Confirm we read all observations:


``` r
nrow(data_gtfsrealtime)
#> [1] 2825902
```

## Comparison with RProtoBuf

### Proto loading

First, we need to read the `.proto` file.


``` r
readProtoFiles2(here::here("src/rust/src/gtfs-realtime.proto"))
```

### Data preparation

The ZIP file contains bzipped protobuf files. `gtfsrealtime` supports this natively, but RProtoBuf does not. So we unzip and uncompress the files first.


``` r
pbdir = tempfile()
dir.create(pbdir)

unzip("nyc-bus-demo.zip", exdir=pbdir)



for (file in list.files(file.path(pbdir, "nyc-bus-demo"), full.names=T)) {
  system2("bunzip2", c(file))
}
```

### The parameters of the test

- Read all of the files in the directory into a list of data frames, one for each file


``` r
input_files = list.files(file.path(pbdir, "nyc-bus-demo"), full.names=T)
stopifnot(length(input_files) == 1440) # minutely for one day
```

### Re-reading with `gtfsrealtime`

We will read the uncompressed files with `gtfsrealtime` to get a fair comparison, without decompression time included, but including the additional file operations RProtoBuf will do. If anything this tilts the field towards RProtoBuf, as the `gtfsrealtime` version is loaded first so files may be e.g. cached by the operating system or hardware.


``` r
system.time({data_gtfsrealtime_uncompressed = lapply(input_files, \(f) read_gtfsrt_positions(f, "America/New_York"))})
#>    user  system elapsed 
#>   6.628   4.520  11.786
```

### Reading with RProtoBuf

Next, we will read them with RProtoBuf:


``` r
system.time({
  data_rpbf = lapply(input_files, \(f) RProtoBuf::read(transit_realtime.FeedMessage, f))
})
#>    user  system elapsed 
#>   2.410   0.401   3.637
```

This is actually significantly faster, but is not a fair comparison. The output of `RProtoBuf::Read` is a hierarchical object, which is notoriously slow and difficult to work with in R, and which will need to be converted to tabular to work with with common, performant libraries in R. The output of `gtfsrealtime` is already in tabular format.

### Reading and converting to tabular format with RProtoBuf

For a truly fair test, we need to also convert the RProtoBuf output to data frames like the GTFS-rt output. We do this two ways, once with a "row-wise" approach where each vehicle position is converted to a data frame and then row-bound, and oncw with a "column-wise" where a single data frame is constructed from columns that are constructed from the hierarchical data with `vapply`. This is still not a completely fair comparison, as it doesn't have some of the features `gtfsrealtime` has, such as ID deduplication or human readable enum columns, but should be close in terms of functionality.

#### Row-wise approach

We define the function to process a single row of the data, and then apply it as part of the reading process





