# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gtfsrealtime_wrappers", use_symbols = TRUE, package_name = "gtfsrealtime")

#' @usage NULL
#' @useDynLib gtfsrealtime, .registration = TRUE
NULL

read_gtfsrt_positions_internal <- function(file) .Call(wrap__read_gtfsrt_positions_internal, file)

enum_TripDescriptor_ScheduleRelationship <- function() .Call(wrap__enum_TripDescriptor_ScheduleRelationship)

enum_VehiclePosition_VehicleStopStatus <- function() .Call(wrap__enum_VehiclePosition_VehicleStopStatus)

enum_VehiclePosition_CongestionLevel <- function() .Call(wrap__enum_VehiclePosition_CongestionLevel)

enum_VehiclePosition_OccupancyStatus <- function() .Call(wrap__enum_VehiclePosition_OccupancyStatus)

read_gtfsrt_trip_updates_internal <- function(file) .Call(wrap__read_gtfsrt_trip_updates_internal, file)

enum_TripUpdate_StopTimeUpdate_ScheduleRelationship <- function() .Call(wrap__enum_TripUpdate_StopTimeUpdate_ScheduleRelationship)

enum_VehicleDescriptor_WheelchairAccessible <- function() .Call(wrap__enum_VehicleDescriptor_WheelchairAccessible)

read_gtfsrt_alerts_internal <- function(file) .Call(wrap__read_gtfsrt_alerts_internal, file)

enum_Alert_Cause <- function() .Call(wrap__enum_Alert_Cause)

enum_Alert_Effect <- function() .Call(wrap__enum_Alert_Effect)

enum_Alert_SeverityLevel <- function() .Call(wrap__enum_Alert_SeverityLevel)

test_data_enum_roundtrip_positions <- function(filename) .Call(wrap__test_data_enum_roundtrip_positions, filename)

test_data_enum_roundtrip_alerts <- function(filename) .Call(wrap__test_data_enum_roundtrip_alerts, filename)

test_data_enum_roundtrip_updates <- function(filename) .Call(wrap__test_data_enum_roundtrip_updates, filename)

test_data_invalid_enum_positions <- function(filename) .Call(wrap__test_data_invalid_enum_positions, filename)

#' Dataset that has two trip updates with
#' id 1: two stop times - should get expanded to two rows,
#' id 2: one stop time - should remain one row,
#' id 3: no stop times which should exist as a single row.
#' @keywords internal
test_data_update_unwrapping <- function(filename) .Call(wrap__test_data_update_unwrapping, filename)

#' Make sure we can read all values in vehicle positions
#' For the other types this is tested incidentally by the unwrapping tests, but there's no unwrapping
#' test for positions since each vehicle position record becomes just one row.
#' @keywords internal
test_data_positions_all_values <- function(filename) .Call(wrap__test_data_positions_all_values, filename)


# nolint end
